#!/usr/bin/env bash
# When passing domain and subdomain parameters,
# display information for the specified subdomain
domain_information () {
    line=$(dig +short "$2"."$1")
    echo "$2 $1 $line" |
    awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
