#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
frontend lb-frontend
	bind *:80
	option httpclose
	option forwardfor
	default_backend lb-backend

backend lb-backend
	mode http
	balance roundrobin
	server 531172-web-01 100.25.223.113:80 check
	server 531172-web-02 52.91.183.15:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

service haproxy start
